// <auto-generated />
using System;
using GorevTakip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GorevTakip.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260530094646_AddIsAdmin")]
    partial class AddIsAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GorevTakip.Models.AltGorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GorevId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Metin")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Tamamlandi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.ToTable("AltGorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Durum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("KategoriId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Oncelik")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Gorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ikon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<int>("Sira")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("GorevTakip.Models.AltGorev", b =>
                {
                    b.HasOne("GorevTakip.Models.Gorev", "Gorev")
                        .WithMany("AltGorevler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gorev");
                });

            modelBuilder.Entity("GorevTakip.Models.Gorev", b =>
                {
                    b.HasOne("GorevTakip.Models.Kategori", "Kategori")
                        .WithMany("Gorevler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GorevTakip.Models.Kullanici", "Kullanici")
                        .WithMany("Gorevler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.HasOne("GorevTakip.Models.Kullanici", "Kullanici")
                        .WithMany("Kategoriler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("GorevTakip.Models.Gorev", b =>
                {
                    b.Navigation("AltGorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kategori", b =>
                {
                    b.Navigation("Gorevler");
                });

            modelBuilder.Entity("GorevTakip.Models.Kullanici", b =>
                {
                    b.Navigation("Gorevler");

                    b.Navigation("Kategoriler");
                });
#pragma warning restore 612, 618
        }
    }
}
